# Important Notes:
# Every field you add must be added to the root build.gradle expandProps map.
# Project
version=35
group=com.mars.morediscs
java_version=17
deimos_version=2.1
# Common
mod_name=More Music Discs
mod_author=Mars
mod_id=morediscs
license=MIT
homepage=https://www.curseforge.com/minecraft/mc-mods/more-mc-music-discs
description=Adds more music discs
minecraft_version=1.18.2
modmenu_version=3.2.5
minecraft_version_range=[1.18, 1.19)
# Fabric
fabric_version=0.77.0+1.18.2
fabric_loader_version=0.16.9
# Forge
forge_version=40.3.0
forge_loader_version_range=[38,)
# Gradle
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
